
services:
  - type: web
    name: ai-content-backend
    env: python
    plan: free
    root: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
